#! /bin/sh
if [ "$#" != "2" ]; then
	echo "Usage: gfs.sh option name"
	echo "option: \n"
	echo "    source         下载软件源代码\n"
	echo "    configure      运行configure或autogen\n"
	echo "    make           编译软件源代码\n"
	echo "    makeclean      运行Makefile中的clean项\n"
	echo "    uninstall      运行Makefile中的uninstall项\n"
	echo "    install        运行Makefile中的install项\n"
	echo "    cd             进入软件源码目录\n"
	echo "    remove         删除软件源码和压缩包\n"
	echo "Notice: \n"
	echo "    我们强烈建议在configure的prefix指定安装位置,好处是\n"
	echo "  当你想要删除软件时,只需要rm -r安装目录即可\n"
	exit
fi
GFS_Name="$2"
GFS_Option="$1"
if [ ! -f "${GFS_SH_PATH}/${GFS_Name}_GFS.sh" ]; then
	echo "没有在${GFS_SH_PATH}下找到执行${GFS_Name}的脚本"
	unset GFS_Name GFS_Option
else
	${GFS_SH_PATH}/${GFS_Name}_GFS.sh ${GFS_Option}
	unset GFS_Name GFS_Option
fi

